### ISSUE TITLE
Should `HCN1` `eh` be `-34.4` or `0.0`?

### ISSUE THREAD

**Issue by Helveg** [dbbs-lab/dbbs-mod-collection#5]
There is a discrepancy in the MOD file for HCN1; it contains a comment for `eh = -34.4`, and no other value is assigned to it, defaulting to `0.0`.

Is this a bug? Which of the 2 values, or what other value should it be?

**Comment by SteMasoli** [comment]
The values in the mod files are used as defaults and they are usually overridden by the values in the models.
If no value is set by the modeler, and no value is set by the mod, then NEURON will default to its own internal values.

In the case of HCN1, during model construction, the value was set to -34.4.

**Comment by Helveg** [comment]
So to use the model we put it to -34.4?
